### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Guy-that-exists** [ChloePrime/AAAParticles#30]
[latest.log](https://github.com/user-attachments/files/17083248/latest.log)

[crash-2024-09-21_03.12.26-client.txt](https://github.com/user-attachments/files/17083245/crash-2024-09-21_03.12.26-client.txt)

**Comment by ChloePrime** [comment]
Fixed in 1.3.1

**Comment by Guy-that-exists** [comment]
> Fixed in 1.3.1

The issue still persists for me when using 1.3.1

[latest.log](https://github.com/user-attachments/files/17088059/latest.log)

**Comment by ChloePrime** [comment]
> > Fixed in 1.3.1
> 
> The issue still persists for me when using 1.3.1
> 
> [latest.log](https://github.com/user-attachments/files/17088059/latest.log)

This is another issue
